Return error code with RuntimeException.
laminas/laminas-cache-storage-adapter-memcached pull request #6
Opened 2021-02-18 06:46 UTC by EreMaijala

This brings parity with other storage adapters that already include the error code in exceptions.

Signed-off-by: Ere Maijala <ere.maijala@helsinki.fi>

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

2021-02-18 12:23 UTC, Ocramius requested changes

2021-02-18 12:23 UTC, Ocramius commented on src/Memcached.php
> +                    $code
Overall OK, but needs a test verifying that this passthrough is preserved, in order to prevent regressions.

2021-02-18 19:33 UTC, boesing commented
I'll add GHA in a PR this weekend. I'll try to rebase this PR afterwards so we can verify the test results here. 👍🏼

2021-04-24 19:41 UTC, boesing commented
Took me a bit but I've added GHA now, added a unit test for your changes and made the tests pass. 👍🏼 
Thanks, @EreMaijala!

2021-04-24 19:41 UTC, boesing approved these changes

2021-04-24 20:05 UTC, boesing commented
@EreMaijala For integrity, I've passed the result code to the other `RuntimeException` creations as well and created tests for that.

2021-04-24 20:06 UTC, merged

2021-04-26 05:25 UTC, EreMaijala commented
@boesing Thanks, I appreciate your extra work and attention to detail. :)